### Swagger ui
GET https://cse341-movies.onrender.com/api-docs

// LOCALHOST - MOVIES

### Get all movies
GET http://localhost:3000/movies HTTP/1.1

### Get movie by id
GET http://localhost:3000/movies/665b8a84132fccb1d04f8c91 HTTP/1.1

### Create new movie
POST http://localhost:3000/movies HTTP/1.1
Content-Type: application/json

{
  "title": "The Awesome Movie",
  "releaseYear": "2024",
  "director": "John Smith",
  "rated": "P",
  "runtime": "90 mins",
  "description": "This is a really awesome movie",
  "cast": [
    "Billy Bob",
    "Donald Duck"
  ],
  "genres": [
    "Adventure",
    "Romance"
  ]
}

### Update movie
PUT http://localhost:3000/movies/665b8f970d62e7781690db52 HTTP/1.1
Content-Type: application/json

{
  "title": "The Cool Movie",
  "releaseYear": "2024",
  "director": "John Smith",
  "rated": "PG-13",
  "runtime": "120 mins",
  "description": "This is a really cool movie",
  "cast": [
    "Billy Bob",
    "Donald Duck",
    "Mickey Mouse"
  ],
  "genres": [
    "Adventure",
    "Romance",
    "Action"
  ]
}

### Delete movie
DELETE http://localhost:3000/movies/665b8f970d62e7781690db52 HTTP/1.1

// RENDER - MOVIES

### Get all movies
GET https://cse341-movies.onrender.com/movies HTTP/1.1

### Get movie by id
GET https://cse341-movies.onrender.com/movies/665b8a84132fccb1d04f8c91 HTTP/1.1

### Create new movie
POST https://cse341-movies.onrender.com/movies HTTP/1.1
Content-Type: application/json

{
  "title": "The Awesome Movie",
  "releaseYear": "2024",
  "director": "John Smith",
  "rated": "PG-13",
  "runtime": "120 mins",
  "description": "This is a really awesome movie",
  "cast": [
    "Billy Bob",
    "Donald Duck"
  ],
  "genres": [
    "Adventure",
    "Romance"
  ]
}

### Update movie
PUT https://cse341-movies.onrender.com/movies/665b8f970d62e7781690db52 HTTP/1.1
Content-Type: application/json

{
  "title": "The Cool Movie",
  "releaseYear": "2024",
  "director": "John Smith",
  "rated": "PG-13",
  "runtime": "120 mins",
  "description": "This is a really cool movie",
  "cast": [
    "Billy Bob",
    "Donald Duck",
    "Mickey Mouse"
  ],
  "genres": [
    "Adventure",
    "Romance",
    "Action"
  ]
}

### Delete movie
DELETE https://cse341-movies.onrender.com/movies/665b8f970d62e7781690db52 HTTP/1.1

// LOCALHOST - USERS

### Get all users
GET http://localhost:3000/users HTTP/1.1

### Get user by id
GET http://localhost:3000/users/665b9145132fccb1d04f8c94 HTTP/1.1

### Create user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "username": "",
  "password": "coolpassword",
  "email": "coolemailemail.com"
}

### Update user
PUT http://localhost:3000/users/665b94eba89101ac2f8db87c HTTP/1.1
Content-Type: application/json

{
  "username": "cool_username",
  "password": "awesome_password",
  "email": "coolemail@email.com"
}

### Delete user
DELETE http://localhost:3000/users/665de4f21e1a2e720868cba3 HTTP/1.1

// RENDER - USERS

### Get all users
GET https://cse341-movies.onrender.com/users HTTP/1.1

### Get user by id
GET https://cse341-movies.onrender.com/users/665b9145132fccb1d04f8c94 HTTP/1.1

### Create user
POST https://cse341-movies.onrender.com/users HTTP/1.1
Content-Type: application/json

{
  "username": "coolusername",
  "password": "coolpassword",
  "email": "coolemail@email.com"
}

### Update user
PUT https://cse341-movies.onrender.com/users/665b94eba89101ac2f8db87c HTTP/1.1
Content-Type: application/json

{
  "username": "cool_username",
  "password": "awesome_password",
  "email": "coolemail@email.com"
}

### Delete user
DELETE https://cse341-movies.onrender.com/users/665b94eba89101ac2f8db87c HTTP/1.1

// LOCALHOST - REVIEWS

### Get all reviews
GET http://localhost:3000/reviews HTTP/1.1

### Get review by id
GET http://localhost3000:/reviews/665b971c132fccb1d04f8c95

### Create review
POST http://localhost:3000/reviews HTTP/1.1
Content-Type: application/json

{
  "movieId": "665b8a84132fccb1d04f8c91",
  "userId": "665b9145132fccb1d04f8c94",
  "score": 4.5,
  "comment": "Great movie!"
}

### Update review
PUT http://localhost:3000/reviews/665b9be6db496e3776ebd6fd HTTP/1.1
Content-Type: application/json

{
  "movieId": "665b8a84132fccb1d04f8c91",
  "userId": "665b9145132fccb1d04f8c94",
  "score": 1,
  "comment": "Bad movie!"
}

### Delete review
DELETE http://localhost:3000/reviews/665b9be6db496e3776ebd6fd HTTP/1.1

// RENDER - REVIEWS

### Get all reviews
GET https://cse341-movies.onrender.com/reviews HTTP/1.1

### Get review by id
GET https://cse341-movies.onrender.com/reviews/665b971c132fccb1d04f8c95

### Create review
POST https://cse341-movies.onrender.com/reviews HTTP/1.1
Content-Type: application/json

{
  "movieId": "665b8a84132fccb1d04f8c91",
  "userId": "665b9145132fccb1d04f8c94",
  "score": 4.5,
  "comment": "Great movie!"
}

### Update review
PUT https://cse341-movies.onrender.com/reviews/665b9be6db496e3776ebd6fd HTTP/1.1
Content-Type: application/json

{
  "movieId": "665b8a84132fccb1d04f8c91",
  "userId": "665b9145132fccb1d04f8c94",
  "score": 1,
  "comment": "Bad movie!"
}

### Delete review
DELETE https://cse341-movies.onrender.com/reviews/665b9be6db496e3776ebd6fd HTTP/1.1